- name: configure catlogue component
  hosts: catalogue
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
      

    - name: enabled nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present     

    - name: create user for catalogue
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    -  name: create app directory
       ansible.builtin.file:
        path: /app
        state: directory


    - name: download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp

    # - name: current directory
    #   ansible.builtin.command: cd /app    

    - name: unzip the catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue-v3.zip
        dest: /app  
        remote_src: yes    

    - name: install nodejs dependencies
      community.general.npm:
        path: /app

    - name: copying catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service    

    - name: deamon reload service
      ansible.builtin.systemd_service:
       deamon_reload: yes

    - name: start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true         

  